### ISSUE TITLE
Duplicate molecules in lines 3608 and 3609

### ISSUE THREAD

**Issue by rgbombarelli** [yangkevin2/coronavirus_data#2]
https://github.com/yangkevin2/coronavirus_data/blob/ab713dd6cd65f75c81046b2e3f1699b4d38ec0a7/data/broad_repurposing_library.csv#L3609

**Comment by rgbombarelli** [comment]
![image](https://user-images.githubusercontent.com/17928525/77380289-1e848000-6d51-11ea-9c05-241e5213881a.png)

**Comment by yangkevin2** [comment]
Thanks, the second has been deleted in all relevant files in data/, conversions/, and 316_AID1706_preds/ in https://github.com/yangkevin2/coronavirus_data/commit/48c20ddd5c6f585e28033d84c855367eb99ad41f .
