### ISSUE TITLE
There's something funky here with the [*] in the SMILES.

### ISSUE THREAD

**Issue by rgbombarelli** [yangkevin2/coronavirus_data#3]
https://github.com/yangkevin2/coronavirus_data/blob/455482b1d5c41393c03b260604e866111b1e8a81/data/expanded_external_library.csv#L976

**Comment by yangkevin2** [comment]
Thanks, SMILES strings with * have been deleted in all relevant files in data/, conversions/, and 316_AID1706_preds/ in https://github.com/yangkevin2/coronavirus_data/commit/48c20ddd5c6f585e28033d84c855367eb99ad41f .
